Repository NCATComp410/comp410_spring_2021, pull requests merged in 2021-04, with the labels that each got.

#105 Added log parser for message ASA-713160, get_low_severity and get_high_severity function
  demo.py
  id_pkg/src/id_parse.py
Labels: Null

#108 Fixed parsing issue with %ASA-6-305011
  id_pkg/src/id_parse.py
Labels: Dream

#110 sprint 4 contributions
  id_pkg/src/id_parse.py
  id_pkg/test/test_suspicious.py
Labels: Ghost
